version: "3"
services:
  mongodb:
    image: mongo
    volumes:
      - products_db:/data/db
    networks:
      - products_network
  api:
    build: .
    image: tiagor87/products-api
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - products_network
  
    
networks:
  products_network:

volumes:
  products_db: